version: 0.2

env:
  variables:
    GOOS: "linux"
phases:
  install:
    commands: 
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
      - echo Moving packages
      - cp -r ./vendor/* /go/
      - ls -al /go/
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build -o app main.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - codedeploy/*
      
