version: 0.2

env:
  variables:
    GOOS: "linux"
phases:
  install:
    run-as: "ubuntu"
    commands: 
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  pre_build:
    run-as: "ubuntu"
    commands: 
      - dep ensure
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build -o app main.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - codedeploy/*
      
