version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build main.go -o app
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - codedeploy/*
      
